---
slug: :mikutter-uwm-hommage
depends:
  mikutter: 3.2.0
  plugin:
  - gtk
version: 0.4.6
author: moguno
name: update_with_media GUI no hazuga...
description: penguin271さんの画像投稿プラグインにGUIを付与するプラグインのはずがいつの間にか単独動作可能になってた。
